language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: huwdZiYgv+L79kPxR+kbyP2tcycWP9W10jhi/nqT3rjsYsnyLVxjycsPpPV4PjsyzkozIOa7gxcktgI1dSREIqavc60qoCmHWTlYQHxdUfCFbnHnReXIG9KqFxKsmps46CUGDk0JQeGWIHh1yAY2OMuLIKJP2Rz7u4BDBT266f24XoPOTa0jvjh4h7mNeW4lWZc062qTbhLRhQ/MRBxdhVbfNfd8hUd8gJMtGfBKVAKDrfwCYw04Fs0/xL/QE+gDandOUdd+O5ukNlVXhKZueD/RgaF0kQ/6yDuxBwn5nPdfr9382alnAdfvO+BfgdO41PNfgVNZO005kwsJ7TrIORThhjOJi7e3RldUOaBRc4jfc51/isPBv53XDbVP8W1VkZgGv0W8hDQQB82ljFFq6Y7cf5qc6rqeo168GmVjTLMQZEfBcwn6bKSMAVVW3Y4DIOZt3jfjvs/+ail7rGXkHjKBuTK+mNboMLhbhBY7YWM9t++vBdz8Bub6UK9o+C1vLiI4vOCLw7C1y/UDV4LgdD2B4gXdff6YwDfWItoGSITUjbXkCFMqSZagCEMSmdKrJb+q5GadVgS09brCA89Omuizvh4L+Y6xR6/EZ9JHHlP6I11u1r1Rp6IEwRJCzgoIqk/5vZenUwmzOR75uxCx7lrC9Y5VyAH5A+5qDePdTSE=
  app: project-survey
  on:
    repo: jmn69/project-survey
