language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: vX64CdIUbIuWR+15tbYqSBymDC8rLdPyfQbgDDJ0LflPTZZUtBjkFss4nwitjKrsRugEzezTLn0nUKGvBXc3rbkmd9zFQ4T7ktpsWo13N5M5/ocHOyzioCB7xwKYKgPKf5xcf4Tadyaqhl1eOhxgjrpwtPh8ntSK6NxSvJV99/elUq+XTCENNoaqLXYuZhYrNCmPuh4sFM2ZJsytZ5g8mufW7z/WOCAVI1RrhUkLMJmcDZ64F2CDpAh8tVEW2/DlNbVMNGMYfYvUptmNwSElAj432HyPln+UND0d2Z1wYMEMQAZffIFXNLCyEhyxQQ6dwDMTmVkygHSF3K5E7LGTljrsQ332W0/wS7M30M12Ef6L+Wr3SZu6KLpAq6g6HSSNIaBO9cM1TG92sQoSdwXNO6XaMyzRUHXaboOMhbD4h6hsSYZu0KlD8Cp2BBT8eOtZlvfQc+dzXp3l5EEctu0rTFzWMUkX1nYJHsMqrBtvEmVsHThsAQPxPtZrzHdZdHI/Ru1z8PTOzeLv2iLF9SfBXmsFp3xdkuSZzs4s5xa+25QxZ68HeDDvPFkQzj0s6L1rJRpKcuOKRKafwL8zp9TJFRi9QaB8B6ICcCLVPT+p201L+OMsU8+rRu38M4GE1bR6U7m2h6thHVXxiS/SNe5Te+HfKenfSOD68p+nfV3ETIg=
