language: node_js
node_js:
- 6
deploy:
  api_key:
    secure: WLJVVDRselwtv3oBBLBRxKnBD6zaAilbkm33WnT20m/hxWPdRg4i8w/FfQQxEFyhoUG9ZtQYLxK49DWUsSKr9kyPzkFiLXH7L83P0vymJWo0SbjmWayYj2TzqFZu2D8wXmKTXS0XaMwh9SBL89PykDa8liiyBTrtYAwVIXxJ2SkStyJdL4eGG2fuDQdvNooTNSfktkmhA+NFyo152JUW+QDON9tV2hzxQbUrcfTOqdaALY4BbbWLshatrJE1WS3bYnMObnqvUHa4XugHxeVJYZNcI6o8S9aZ4qP5zYDNHTSCLycxnJQd/Ll0ipbSlg6ydZDfE8d4f1DgGxLAO+Kw4WkF+dmFzFrqio9Mi954zHN8ZZIY2S/aNGOF+frmGtlhKAu8kvVNPePGU7EsnslKAXF8JyjVBSSUk5MKqSqZjDjf2OiINcJotRXWM+h5Lf8nMZUKISLiLaZjaQFe/RBLbxZyOhywJbjZnU9H23yVvaj66F5ecUjd4fDlfdUA5NaGOUhvSVIZSeR3bDSl4/26N0hpKO3d0LBEy5GUnoY7zdugwEriCA/jaM3FJR0skpY9+LB+Ii5O3pJQWOTxAQ93jxsrLY2mZSoWsP+FU75uznTZeHyaX1nP2kUvo9SzovbBbcNSOOJBxaHOuXWnHsZ8UdxofgPEAuHMtmSOhBKQJy4=
